package dev.greenhouseteam.rapscallionsandrockhoppers.client.renderer.model;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class PenguinAnimation {
    public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(2f).looping()
        .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(1.5f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("brow",
                new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.1f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("leftFlipper",
                new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("leftFlipper",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("rightFlipper",
                new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("rightFlipper",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.POSITION,
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.15f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR))).build();

    public static final AnimationDefinition SHOCK_ARMS = AnimationDefinition.Builder.withLength(0.48f).looping()
            .addAnimation("leftFlipper",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.12f, KeyframeAnimations.degreeVec(0f, 0f, -30f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 0f, 30f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rightFlipper",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.12f, KeyframeAnimations.degreeVec(0f, 0f, 30f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 0f, -30f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();

    public static final AnimationDefinition WADDLE_ARMS_EXTEND = AnimationDefinition.Builder.withLength(0.48f)
            .addAnimation("leftFlipper",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, -40f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rightFlipper",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 40f),
                                    AnimationChannel.Interpolations.LINEAR))).build();

    public static final AnimationDefinition WADDLE_ARMS_RETRACT = AnimationDefinition.Builder.withLength(0.48f)
            .addAnimation("leftFlipper",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -40f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rightFlipper",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 40f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();

    public static final AnimationDefinition WADDLE_FEET = AnimationDefinition.Builder.withLength(1.84f).looping()
            .addAnimation("leftFoot",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 1f, 0.45f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.44f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.64f, KeyframeAnimations.posVec(0f, -0.5f, -2.25f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.72f, KeyframeAnimations.posVec(0f, -0.05f, -0.95f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.92f, KeyframeAnimations.posVec(0f, 0f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.16f, KeyframeAnimations.posVec(0f, 1f, 0.45f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.36f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.56f, KeyframeAnimations.posVec(0f, -0.5f, -2.25f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.64f, KeyframeAnimations.posVec(0f, -0.05f, -0.95f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.84f, KeyframeAnimations.posVec(0f, -0.02f, 1.13f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("leftFoot",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.44f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.64f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.72f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.92f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.16f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.56f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.64f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rightFoot",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.2f, 0.09f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.04f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24f, KeyframeAnimations.posVec(0f, -0.5f, -2.25f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.32f, KeyframeAnimations.posVec(0f, -0.05f, -0.95f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.52f, KeyframeAnimations.posVec(0f, 0f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.64f, KeyframeAnimations.posVec(0f, 1f, 0.45f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.84f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.04f, KeyframeAnimations.posVec(0f, -0.5f, -2.25f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.12f, KeyframeAnimations.posVec(0f, -0.05f, -0.95f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.32f, KeyframeAnimations.posVec(0f, 0f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.56f, KeyframeAnimations.posVec(0f, 1f, 0.45f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.84f, KeyframeAnimations.posVec(0f, 0.2f, 0.09f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rightFoot",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.04f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.64f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.04f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.32f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.56f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.84f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();

    public static final AnimationDefinition WADDLE_BODY = AnimationDefinition.Builder.withLength(1.84f).looping()
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, -8f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, -5.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 8f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.72f, KeyframeAnimations.degreeVec(0f, 0f, 5.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.92f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.08f, KeyframeAnimations.degreeVec(0f, 0f, -8f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.16f, KeyframeAnimations.degreeVec(0f, 0f, -5.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.56f, KeyframeAnimations.degreeVec(0f, 0f, 8f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.64f, KeyframeAnimations.degreeVec(0f, 0f, 5.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16f, KeyframeAnimations.posVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24f, KeyframeAnimations.posVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.64f, KeyframeAnimations.posVec(-1f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.72f, KeyframeAnimations.posVec(-1f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.92f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.08f, KeyframeAnimations.posVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.16f, KeyframeAnimations.posVec(1f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.56f, KeyframeAnimations.posVec(-1f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.64f, KeyframeAnimations.posVec(-1f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.84f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 11f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, 8.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, -11f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.72f, KeyframeAnimations.degreeVec(0f, 0f, -8.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.92f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.08f, KeyframeAnimations.degreeVec(0f, 0f, 11f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.16f, KeyframeAnimations.degreeVec(0f, 0f, 8.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.56f, KeyframeAnimations.degreeVec(0f, 0f, -11f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.64f, KeyframeAnimations.degreeVec(0f, 0f, -8.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
}
