modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/GreenhouseTeam/rapscallions-and-rockhoppers/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/rapscallions-and-rockhoppers/forge_updates.json"
displayURL="https://modrinth.com/mod/rapscallions-and-rockhoppers"
logoFile="${mod_id}.png"
credits="MerchantPug, Omniv, UltrusBot"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "smartbrainlib"
type = "required"
versionRange = "${sbl_version_range}"
ordering = "NONE"
side = "BOTH"